kind: DaemonSet
apiVersion: apps/v1beta2
metadata:
  name: csi-openebs
spec:
  selector:
    matchLabels:
      app: csi-openebs
  template:
    metadata:
      labels:
        app: csi-openebs
    spec:
      serviceAccount: csi-openebs
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
        - name: csi-openebs
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: openebs/openebs-csi-plugin:v0.0.1
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--token=$(OPENEBS_ACCESS_TOKEN)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: OPENEBS_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: openebstoken
                  key: token
          imagePullPolicy: "Always"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - mountPath: /dev
              name: device-dir
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/openebs-csi/
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
